#########################################本地开发环境#########################################
spring:
  application:
  name: "platform-sms-server"
  profiles:
    active: prod

server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: "UTF-8"
      enabled: true
      force: true

logging:
  config: "classpath:logback.xml"


