#########################################本地开发环境#########################################
spring:
  application:
  name: "platform-sms-server"
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: test

server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: "UTF-8"
      enabled: true
      force: true

logging:
  config: "classpath:logback-spring.xml"

mybatis:
  mapper-locations: classpath:mapper/*DAO.xml
  type-aliases-package: com.courage.platform.sms.domain

