#########################################本地开发环境#########################################
spring:
  application:
  name: "platform-sms-worker"
  profiles:
    active: prod

server:
  port: 8082
  servlet:
    context-path: /
    encoding:
      enabled: true
      charset: "UTF-8"
      force: true

logging:
  config: "classpath:logback.xml"


